import{useEffect,useMemo,useState}from'react'
import{Link}from'react-router-dom'
import{api}from'../lib/api'
import{printBM183,printBM184}from'../lib/printForms'
const labels:Record<string,string>={received:'Đã tiếp nhận',pending_supplier:'Chờ chuyển/NCC xử lý',sent_supplier:'Đã chuyển nhà cung cấp',supplier_returned:'NCC đã trả hàng',ready_for_customer:'Sẵn sàng trả khách',returned_customer:'Đã trả khách',cancelled:'Đã hủy'}
export default function Cases(){const[rows,setRows]=useState<any[]>([]),[status,setStatus]=useState(''),[q,setQ]=useState(''),[err,setErr]=useState(''),[selected,setSelected]=useState<string[]>([]);async function load(){try{const d=await api<any>({action:'list_cases',status:status||undefined});setRows(d.rows||[])}catch(e:any){setErr(e.message)}}useEffect(()=>{void load()},[status]);const filtered=useMemo(()=>{const k=q.trim().toLowerCase();if(!k)return rows;return rows.filter(r=>[r.case_code,r.customer?.full_name,r.customer?.phone,r.product?.name,r.product?.sku,r.product?.serial_number,r.issue_description].some(v=>String(v||'').toLowerCase().includes(k)))},[rows,q]);const chosen=rows.filter(r=>selected.includes(r.id));async function log(code:string,payload:any){try{await api({action:'log_document',form_code:code,template_version:'official-source',snapshot_data:payload})}catch{}}
function bm184(){printBM184(rows,new Date());void log('BM-184.KD',{month:new Date().toISOString().slice(0,7),case_count:rows.length})}
function bm183(){if(!chosen.length){setErr('Chọn ít nhất một hồ sơ để lập BM-183.');return}printBM183(chosen);void log('BM-183.KD',{case_ids:chosen.map(r=>r.id),case_codes:chosen.map(r=>r.case_code)})}
const allChecked=filtered.length>0&&filtered.every(r=>selected.includes(r.id));function toggleAll(){setSelected(allChecked?selected.filter(id=>!filtered.some(r=>r.id===id)):Array.from(new Set([...selected,...filtered.map(r=>r.id)])))}
return <><div className="page-head legacy-page-head"><div><h1>Hồ sơ bảo hành</h1><p>Quản lý toàn bộ vòng đời hồ sơ</p></div></div>{err&&<div className="alert danger">{err}</div>}<div className="card cases-card"><div className="cases-toolbar"><div className="search-input-wrap">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm số phiếu, khách hàng, điện thoại, sản phẩm, serial…"/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tất cả trạng thái</option><option value="received">Đã tiếp nhận</option><option value="pending_supplier">Chờ chuyển/NCC xử lý</option><option value="sent_supplier">Đã chuyển nhà cung cấp</option><option value="supplier_returned">NCC đã trả hàng</option><option value="ready_for_customer">Sẵn sàng trả khách</option><option value="returned_customer">Đã trả khách</option><option value="cancelled">Đã hủy</option></select><button className="ghost print-btn" onClick={bm184}>▣&nbsp; In BM-184 tháng này</button></div><div className="batch-form-bar"><div><b>BM-183 – Chuyển NCC</b><span>{selected.length?`Đã chọn ${selected.length} hồ sơ`:'Tick các hồ sơ cần chuyển cùng đợt'}</span></div><button className="ghost" onClick={bm183} disabled={!selected.length}>In BM-183 ({selected.length})</button></div><div className="table-wrap old-case-table"><table><thead><tr><th className="check-col"><input aria-label="Chọn tất cả" type="checkbox" checked={allChecked} onChange={toggleAll}/></th><th>SỐ HỒ SƠ</th><th>KHÁCH HÀNG</th><th>SẢN PHẨM</th><th>NGÀY NHẬN</th><th>HẸN TRẢ</th><th>TRẠNG THÁI</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td className="check-col"><input aria-label={`Chọn ${r.case_code}`} type="checkbox" checked={selected.includes(r.id)} onChange={e=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(x=>x!==r.id))}/></td><td><Link to={`/case/${r.id}`}>{r.case_code}</Link></td><td>{r.customer?.full_name||'—'}<small>{r.customer?.phone||''}</small></td><td>{r.product?.name||'—'}<small>{r.product?.serial_number||r.product?.sku||''}</small></td><td>{r.received_at?new Date(r.received_at).toLocaleDateString('vi-VN'):'—'}</td><td>{r.promised_return_at?new Date(r.promised_return_at).toLocaleDateString('vi-VN'):'—'}</td><td><span className={`status-pill status-${r.status}`}>{labels[r.status]||r.status}</span></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty-dashboard case-empty"><div className="empty-icon">▤</div><span>Không tìm thấy hồ sơ phù hợp</span></div>}</div></div></>}
