import{useEffect,useState}from'react';import{Link}from'react-router-dom';import{api}from'../lib/api'
const statusLabel:Record<string,string>={received:'Đã tiếp nhận',processing:'Đang xử lý',waiting_supplier:'Chờ nhà cung cấp',ready_return:'Sẵn sàng trả',returned:'Đã trả khách',closed:'Đã hoàn tất'}
export default function Dashboard(){const[data,setData]=useState<any>(null),[err,setErr]=useState('');useEffect(()=>{api({action:'dashboard'}).then(setData).catch(e=>setErr(e.message))},[]);return <>
  <div className="dashboard-title"><div className="coop-label">CO.OPMART</div><h1>Tổng quan bảo hành</h1><p>Theo dõi nhanh tình trạng tiếp nhận và lịch xử lý.</p></div>{err&&<div className="alert danger">{err}</div>}
  <div className="dashboard-grid">
    <div className="dash-card"><span>Hồ sơ đang xử lý</span><b>{data?.stats?.open_cases??'—'}</b><small>Tất cả trạng thái chưa hoàn tất</small></div>
    <div className="dash-card"><span>Chờ nhà cung cấp</span><b>{data?.stats?.waiting_supplier??'—'}</b><small>Cần theo dõi tiến độ NCC/TTBH</small></div>
    <div className="dash-card accent-warn"><span>Sắp đến lịch hẹn</span><b>{data?.stats?.upcoming??'—'}</b><small>Lịch gần nhất · cần theo dõi</small></div>
    <div className="dash-card accent-danger"><span>Quá hạn trả khách</span><b>{data?.stats?.overdue??'—'}</b><small>Hồ sơ quá ngày hẹn chưa trả</small></div>
  </div>
  <section className="card dashboard-section"><div className="section-title"><div><h2>Hồ sơ mới tiếp nhận</h2><p>Cập nhật gần nhất</p></div><Link to="/cases">Xem tất cả</Link></div>{(data?.recent||[]).length?<div className="recent-list">{data.recent.map((r:any)=><Link className="recent-row" to={`/case/${r.id}`} key={r.id}><div><b>{r.case_code}</b><span>{r.customer?.full_name} · {r.product?.name}</span><small>{r.issue_description}</small></div><div><span className="badge">{statusLabel[r.status]||r.status}</span><small>{r.received_at?new Date(r.received_at).toLocaleDateString('vi-VN'):''}</small></div></Link>)}</div>:<div className="empty-dashboard">Chưa có hồ sơ mới tiếp nhận</div>}</section>
  <section className="card dashboard-section"><div className="section-title"><div><h2>Lịch sắp tới</h2><p>Ngày chuyển NCC và trả khách</p></div></div>{(data?.upcoming_appointments||[]).length?<div className="recent-list">{data.upcoming_appointments.map((a:any)=><Link className="recent-row" to={`/case/${a.service_case_id}`} key={a.id}><div><b>{a.case?.case_code||'Lịch hẹn'}</b><span>{a.case?.customer?.full_name} · {a.case?.product?.name}</span><small>{a.note||'Không có ghi chú'}</small></div><div><b>{new Date(a.scheduled_at).toLocaleString('vi-VN')}</b><small>{a.appointment_type==='supplier'?'Nhà cung cấp':'Trả/trao đổi với khách'}</small></div></Link>)}</div>:<div className="empty-dashboard"><div className="empty-icon">▤</div><span>Chưa có lịch hẹn sắp tới</span></div>}</section>
</>}
