import{FormEvent,useState}from'react';import{api,uploadAttachment}from'../lib/api';import{addMonths}from'../lib/date'
type Item={name:string;sku:string;brand:string;model:string;serial_number:string;warranty_months:number;warranty_card_number:string};const blank=():Item=>({name:'',sku:'',brand:'',model:'',serial_number:'',warranty_months:12,warranty_card_number:''})
const Step=({n,title,sub}:{n:string,title:string,sub:string})=><div className="step-title wide"><span>{n}</span><div><h2>{title}</h2><p>{sub}</p></div></div>
export default function NewWarranty(){const[customerName,setCustomerName]=useState(''),[phone,setPhone]=useState(''),[address,setAddress]=useState(''),[invoice,setInvoice]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[items,setItems]=useState<Item[]>([blank()]),[file,setFile]=useState<File|null>(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);const patch=(i:number,k:keyof Item,v:any)=>setItems(x=>x.map((a,j)=>j===i?{...a,[k]:v}:a));async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMsg('');try{const result=await api<any>({action:'create_warranty',customer_name:customerName,phone,address,invoice_number:invoice,purchase_date:date,items:items.map(i=>({...i,warranty_end_date:addMonths(date,i.warranty_months)}))});if(file&&result.product_ids?.[0])await uploadAttachment(file,{product_id:result.product_ids[0],kind:'receipt'});setMsg(`Đã lưu ${result.product_ids.length} sản phẩm bảo hành.`);setCustomerName('');setPhone('');setAddress('');setInvoice('');setItems([blank()]);setFile(null)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}return <><div className="page-head legacy-page-head"><div><h1>Tạo bảo hành mua mới</h1><p>Lưu thông tin sản phẩm và ảnh hóa đơn</p></div></div><form className="legacy-form" onSubmit={submit}>
<section className="card form-grid step-card"><Step n="01" title="Thông tin khách hàng" sub="Số điện thoại dùng làm khóa tra cứu chính"/><label>Họ và tên khách hàng *<input required value={customerName} onChange={e=>setCustomerName(e.target.value)}/></label><label>Số điện thoại *<input required inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="wide">Địa chỉ<input value={address} onChange={e=>setAddress(e.target.value)}/></label></section>
<section className="card form-grid step-card"><Step n="02" title="Thông tin sản phẩm" sub={`${items.length} sản phẩm trong hóa đơn này`}/>{items.map((it,i)=><div className="item-box wide legacy-item" key={i}><div className="item-number">Sản phẩm {i+1}</div><div className="item-grid legacy-item-grid"><label className="item-name">Tên sản phẩm *<input required value={it.name} onChange={e=>patch(i,'name',e.target.value)}/></label><label>Mã hàng/SKU<input value={it.sku} onChange={e=>patch(i,'sku',e.target.value)}/></label><label>Thương hiệu/NCC<input value={it.brand} onChange={e=>patch(i,'brand',e.target.value)}/></label><label>Model<input value={it.model} onChange={e=>patch(i,'model',e.target.value)}/></label><label>Serial No./IMEI<input value={it.serial_number} onChange={e=>patch(i,'serial_number',e.target.value)}/></label><label>Số phiếu bảo hành<input value={it.warranty_card_number} onChange={e=>patch(i,'warranty_card_number',e.target.value)}/></label><label>Thời hạn BH (tháng)<input type="number" min="1" max="120" value={it.warranty_months} onChange={e=>patch(i,'warranty_months',Number(e.target.value)||1)}/></label><label>Hết hạn bảo hành<input readOnly value={addMonths(date,it.warranty_months)}/></label></div>{items.length>1&&<div className="row-actions"><span></span><button type="button" className="ghost" onClick={()=>setItems(x=>x.filter((_,j)=>j!==i))}>Xóa sản phẩm</button></div>}</div>)}<div className="wide"><button type="button" className="ghost add-item" onClick={()=>setItems(x=>[...x,blank()])}>＋ Thêm sản phẩm trong cùng hóa đơn</button></div></section>
<section className="card form-grid step-card"><Step n="03" title="Hóa đơn & thời gian bảo hành" sub="Lưu chứng từ để khách không cần giữ hóa đơn giấy"/><label>Mã hóa đơn<input value={invoice} onChange={e=>setInvoice(e.target.value)}/></label><label>Ngày mua<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="wide file-drop">Ảnh hóa đơn<input type="file" accept="image/*" capture="environment" onChange={e=>setFile(e.target.files?.[0]||null)}/><small>{file?`Đã chọn: ${file.name}`:'Có thể chụp trực tiếp bằng điện thoại hoặc chọn ảnh có sẵn.'}</small></label></section>
<section className="card form-actions-card">{msg&&<div className="alert">{msg}</div>}<div className="actions"><span className="muted">Kiểm tra thông tin trước khi lưu.</span><button className="primary large-action" disabled={busy}>{busy?'Đang lưu…':'Lưu bảo hành mua mới'}</button></div></section>
</form></>}
