import {FormEvent,useEffect,useMemo,useState} from 'react'
import {Link,useNavigate} from 'react-router-dom'
import {api,uploadAttachment} from '../lib/api'

type Product={id:string;name:string;sku?:string;brand?:string;model?:string;serial_number?:string;purchase_date?:string;warranty_end_date?:string;warranty_card_number?:string;invoice_number?:string;customer?:{full_name?:string;phone?:string;address?:string}}
type Staff={id:string;full_name?:string;employee_code?:string;department?:string}
const localDateTime=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
const toIso=(value:string)=>value?new Date(value).toISOString():null
const money=(v:string)=>v?Number(v.replace(/[^0-9]/g,'')):null
const Step=({n,title,sub}:{n:string,title:string,sub:string})=><div className="step-title wide"><span>{n}</span><div><h2>{title}</h2><p>{sub}</p></div></div>

export default function ReceiveFaulty(){
  const nav=useNavigate();const[q,setQ]=useState(''),[rows,setRows]=useState<Product[]>([]),[selected,setSelected]=useState<Product|null>(null)
  const[loading,setLoading]=useState(false),[msg,setMsg]=useState(''),[files,setFiles]=useState<File[]>([]),[staff,setStaff]=useState<Staff[]>([])
  const[form,setForm]=useState({case_code:'',issue_description:'',condition_description:'',cause_category:'',service_type:'warranty',estimated_fee:'',supplier_name:'',received_at:localDateTime(),promised_return_at:'',assigned_to:'',has_warranty_card:false,is_sealed:false,has_wrapping:false,has_box:false,notes:''})
  useEffect(()=>{api<{staff:Staff[]}>({action:'case_form_options'}).then(d=>setStaff(d.staff||[])).catch(()=>{})},[])
  const warrantyState=useMemo(()=>{if(!selected?.warranty_end_date)return 'Chưa có ngày hết bảo hành';const end=new Date(selected.warranty_end_date+'T23:59:59');return end>=new Date()?`Còn bảo hành đến ${new Date(selected.warranty_end_date).toLocaleDateString('vi-VN')}`:`Đã hết bảo hành từ ${new Date(selected.warranty_end_date).toLocaleDateString('vi-VN')}`},[selected])
  async function search(e?:FormEvent){e?.preventDefault();setMsg('');if(!q.trim()){setMsg('Nhập SĐT, mã hóa đơn, SKU, Serial/IMEI hoặc tên sản phẩm.');return}try{setLoading(true);const d=await api<any>({action:'search',q:q.trim()});setRows(d.products||[]);if(!(d.products||[]).length)setMsg('Không tìm thấy sản phẩm đã lưu. Có thể tạo bảo hành mua mới trước rồi tiếp nhận hàng lỗi.')}catch(e:any){setMsg(e.message)}finally{setLoading(false)}}
  async function submit(e:FormEvent){e.preventDefault();if(!selected)return;try{setLoading(true);setMsg('');const d=await api<any>({action:'create_case',product_id:selected.id,case_code:form.case_code,issue_description:form.issue_description,condition_description:form.condition_description,cause_category:form.cause_category,service_type:form.service_type,estimated_fee:money(form.estimated_fee),supplier_name:form.supplier_name,received_at:toIso(form.received_at),promised_return_at:toIso(form.promised_return_at),assigned_to:form.assigned_to||null,has_warranty_card:form.has_warranty_card,is_sealed:form.is_sealed,has_wrapping:form.has_wrapping,has_box:form.has_box,notes:form.notes});for(const file of files)await uploadAttachment(file,{service_case_id:d.id,product_id:selected.id,kind:'service'});nav(`/case/${d.id}`)}catch(e:any){setMsg(e.message)}finally{setLoading(false)}}
  return <><div className="page-head legacy-page-head"><div><h1>Tiếp nhận sản phẩm lỗi</h1><p>Lập biên nhận, ghi nhận hiện trạng và lịch hẹn</p></div></div>
    <section className="card step-card receive-customer-card"><Step n="01" title="Tìm khách hàng" sub="Kiểm tra dữ liệu cũ trước khi lập hồ sơ"/><form className="wide legacy-receive-search" onSubmit={search}><div className="search-input-wrap">⌕<input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Nhập số điện thoại khách hàng, mã hóa đơn, SKU hoặc Serial"/></div><button className="primary" disabled={loading}>{loading?'Đang tìm…':'Tìm khách hàng / sản phẩm'}</button></form>{msg&&!selected&&<div className="alert wide">{msg}</div>}{!selected&&!!rows.length&&<div className="wide receive-results">{rows.map(r=><button type="button" className="pick-row" key={r.id} onClick={()=>{setSelected(r);setMsg('')}}><div><b>{r.customer?.full_name||'Khách hàng'} · {r.name}</b><span>{r.customer?.phone||'—'}{r.customer?.address?` · ${r.customer.address}`:''}</span><small>{[r.invoice_number&&`HĐ ${r.invoice_number}`,r.sku&&`SKU ${r.sku}`,r.serial_number&&`Serial ${r.serial_number}`].filter(Boolean).join(' · ')||'Chưa có mã nhận dạng'}</small></div><span className="pick-arrow">›</span></button>)}</div>}{selected&&<div className="wide customer-summary"><div><label>Họ và tên khách hàng</label><strong>{selected.customer?.full_name||'—'}</strong></div><div><label>Số điện thoại</label><strong>{selected.customer?.phone||'—'}</strong></div><div className="wide-summary"><label>Địa chỉ</label><strong>{selected.customer?.address||'—'}</strong></div><button type="button" className="ghost" onClick={()=>setSelected(null)}>Chọn lại khách / sản phẩm</button></div>}</section>
    {selected&&<form className="legacy-form receive-legacy-form" onSubmit={submit}>
      <section className="card form-grid step-card"><Step n="02" title="Chọn sản phẩm" sub="Thông tin mua hàng đã lưu trên hệ thống"/><label>Tên sản phẩm<input readOnly value={selected.name||''}/></label><label>Thương hiệu/NCC<input readOnly value={selected.brand||''}/></label><label>Model<input readOnly value={selected.model||''}/></label><label>Serial No./IMEI<input readOnly value={selected.serial_number||''}/></label><label>Số phiếu bảo hành<input readOnly value={selected.warranty_card_number||''}/></label><label>Mã hóa đơn<input readOnly value={selected.invoice_number||''}/></label><div className="wide warranty-banner">{warrantyState}</div></section>
      <section className="card form-grid step-card"><Step n="03" title="Tình trạng và hướng xử lý" sub="Ghi nhận đầy đủ hiện trạng lúc tiếp nhận"/><label>Mã hồ sơ<input value={form.case_code} onChange={e=>setForm({...form,case_code:e.target.value})} placeholder="Để trống để hệ thống tự tạo"/></label><label>Thời điểm tiếp nhận *<input required type="datetime-local" value={form.received_at} onChange={e=>setForm({...form,received_at:e.target.value})}/></label><label className="wide">Mô tả lỗi / yêu cầu khách hàng *<textarea required rows={3} value={form.issue_description} onChange={e=>setForm({...form,issue_description:e.target.value})} placeholder="Ví dụ: Không lên nguồn, màn hình chớp, khách yêu cầu kiểm tra bảo hành…"/></label><label className="wide">Tình trạng ngoại quan khi nhận<textarea rows={3} value={form.condition_description} onChange={e=>setForm({...form,condition_description:e.target.value})} placeholder="Trầy xước, móp, bể, thiếu phụ kiện, tem niêm phong…"/></label><label>Nhóm nguyên nhân / lỗi<select value={form.cause_category} onChange={e=>setForm({...form,cause_category:e.target.value})}><option value="">Chưa xác định</option><option value="technical">Lỗi kỹ thuật</option><option value="physical">Hư hỏng ngoại quan</option><option value="accessory">Phụ kiện</option><option value="usage">Hướng dẫn sử dụng</option><option value="supplier">Chờ NCC/TTBH xác định</option><option value="other">Khác</option></select></label><label>Hình thức xử lý<select value={form.service_type} onChange={e=>setForm({...form,service_type:e.target.value})}><option value="warranty">Bảo hành</option><option value="repair">Sửa chữa</option><option value="exchange">Đổi hàng / kiểm tra đổi</option><option value="inspection">Kiểm tra kỹ thuật</option></select></label><label>Nhà cung cấp / TTBH<input value={form.supplier_name} onChange={e=>setForm({...form,supplier_name:e.target.value})}/></label><label>Chi phí dự kiến<input inputMode="numeric" value={form.estimated_fee} onChange={e=>setForm({...form,estimated_fee:e.target.value.replace(/[^0-9]/g,'')})} placeholder="0"/></label></section>
      <section className="card form-grid step-card"><Step n="04" title="Lịch hẹn & bàn giao" sub="Thông tin theo dõi sau khi nhận hàng"/><label>Hẹn trả khách / hoàn tất<input type="datetime-local" value={form.promised_return_at} onChange={e=>setForm({...form,promised_return_at:e.target.value})}/></label><label>Nhân viên phụ trách<select value={form.assigned_to} onChange={e=>setForm({...form,assigned_to:e.target.value})}><option value="">Chưa phân công</option>{staff.map(s=><option key={s.id} value={s.id}>{s.full_name||s.employee_code||s.id}{s.employee_code?` · ${s.employee_code}`:''}</option>)}</select></label><div className="wide accessory-box"><b>Giấy tờ / phụ kiện nhận kèm</b><div className="check-grid"><label><input type="checkbox" checked={form.has_warranty_card} onChange={e=>setForm({...form,has_warranty_card:e.target.checked})}/> Có phiếu bảo hành</label><label><input type="checkbox" checked={form.is_sealed} onChange={e=>setForm({...form,is_sealed:e.target.checked})}/> Còn tem/niêm phong</label><label><input type="checkbox" checked={form.has_wrapping} onChange={e=>setForm({...form,has_wrapping:e.target.checked})}/> Có bao bì/phụ kiện</label><label><input type="checkbox" checked={form.has_box} onChange={e=>setForm({...form,has_box:e.target.checked})}/> Có hộp sản phẩm</label></div></div><label className="wide file-drop">Ảnh hàng lỗi / phụ kiện / phiếu nhận<input type="file" multiple accept="image/*" capture="environment" onChange={e=>setFiles(Array.from(e.target.files||[]))}/><small>{files.length?`Đã chọn ${files.length} file`:'Có thể chụp nhiều ảnh khi tiếp nhận.'}</small></label><label className="wide">Ghi chú nội bộ<textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></section>
      <section className="card form-actions-card">{msg&&<div className="alert">{msg}</div>}<div className="actions"><Link className="ghost button-link" to="/cases">Hồ sơ bảo hành</Link><button className="primary large-action" disabled={loading}>{loading?'Đang lưu hồ sơ…':'Hoàn tất tiếp nhận'}</button></div></section>
    </form>}
  </>
}
